application: jgaappsales
version: 1
runtime: python
api_version: 1

handlers:
- url: /ui
  static_dir: ui

- url: /jobs/pull_rankings
  script: /jobs/pull_rankings.py
  login: admin

- url: /jobs/pull_rankings/worker
  script: /jobs/pull_rankings.py
  login: admin

- url: /jobs/pull_report
  script: /jobs/pull_report.py
  login: admin

- url: /jobs/pull_ratings
  script: /jobs/pull_ratings.py
  login: admin

- url: /jobs/pull_ratings/worker
  script: /jobs/pull_ratings.py
  login: admin

- url: /jobs/email_report
  script: /jobs/email_report.py
  login: admin

- url: /report/.*
  script: /report/report.py
  login: admin

- url: /api/.*
  script: /handlers/api.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /(.*\.manifest)
  static_files: manifests/\1
  upload: manifests/(.*\.manifest)
  mime_type: text/cache-manifest

- url: .*
  script: main.py
  login: admin


